using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ONT_PROJECT.Models;
using Microsoft.AspNetCore.Http;

namespace ONT_PROJECT.Controllers
{
    public class ManagerReportController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public ManagerReportController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            var medicines = _context.Medicines
                .Include(m => m.Form)
                .Include(m => m.Supplier)
                .Select(m => new
                {
                    m.MedicineId,
                    m.MedicineName,
                    FormName = m.Form != null ? m.Form.FormName : null,
                    SupplierName = m.Supplier != null ? m.Supplier.Name : null
                })
                .ToList();

            return View(medicines);
        }

        [HttpPost]
        public IActionResult GenerateReport(
            string GroupBy,
            string FilterValue,                     
            List<int> SelectedMedications,
            DateTime ReportDate,
            string StockLevel)
        {
            var firstName = _httpContextAccessor.HttpContext.Session.GetString("UserFirstName") ?? "";
            var lastName = _httpContextAccessor.HttpContext.Session.GetString("UserLastName") ?? "";
            var managerName = $"{firstName} {lastName}".Trim();

            if (ReportDate == default)
                ReportDate = DateTime.Now;

            var query = _context.Medicines.Include(m => m.Form)
                                          .Include(m => m.Supplier)
                                          .AsQueryable();

            if (!string.IsNullOrEmpty(FilterValue))
            {
                if (GroupBy == "Supplier")
                    query = query.Where(m => m.Supplier.Name == FilterValue);
                else if (GroupBy == "DosageForm")
                    query = query.Where(m => m.Form.FormName == FilterValue);
            }

            if (SelectedMedications != null && SelectedMedications.Any() && !SelectedMedications.Contains(-1))
                query = query.Where(m => SelectedMedications.Contains(m.MedicineId));

            if (StockLevel == "low")
                query = query.Where(m => m.Quantity <= m.ReorderLevel);
            else if (StockLevel == "out")
                query = query.Where(m => m.Quantity == 0);

            var medicines = query.ToList();

            IEnumerable<IGrouping<string, Medicine>> grouped = GroupBy switch
            {
                "DosageForm" => medicines.GroupBy(m => m.Form?.FormName ?? "Unknown"),
                "Schedule" => medicines.GroupBy(m => m.Schedule.ToString()),
                "Supplier" => medicines.GroupBy(m => m.Supplier?.Name ?? "Unknown"),
                _ => new List<IGrouping<string, Medicine>>() { medicines.GroupBy(m => "All").FirstOrDefault() }
            };

            var pdfBytes = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(2, Unit.Centimetre);

                    page.Header().Row(row =>
                    {
                        row.ConstantItem(100).Image("wwwroot/images/logo_2-removebg-preview.png");
                        row.RelativeItem().Column(col =>
                        {
                            col.Item().Text("Ibhayi Pharmacy").FontSize(24).Bold().FontColor(Colors.Blue.Darken2);
                            col.Item().Text($"Pharmacy Manager Report - {ReportDate:dd/MM/yyyy}").FontSize(16).SemiBold();
                            col.Item().Text($"Generated by: {managerName}").FontSize(12).Italic().FontColor(Colors.Grey.Darken2);
                        });
                    });

                    page.Content().PaddingVertical(10).Column(column =>
                    {
                        string heading = GroupBy switch
                        {
                            "Supplier" => "Stock by Supplier",
                            "Schedule" => "Stock by Schedule",
                            "DosageForm" => "Stock by Dosage Form",
                            _ => "Stock Report"
                        };
                        column.Item().Container()
                             .PaddingBottom(10)
                             .Text(heading)
                             .FontSize(18)
                             .Bold()
                             .FontColor(Colors.Black)
                             .Underline();

                        foreach (var group in grouped)
                        {
                            if (!group.Any())
                                continue;

                            column.Item().Element(container =>
                            {
                                container.Column(col =>
                                {
                                    col.Item().Text($"{GroupBy}: {group.Key}")
                                        .FontSize(14).Bold().FontColor(Colors.Black).Underline();

                                    col.Item().Table(table =>
                                    {
                                        bool showScheduleColumn = GroupBy != "Schedule";

                                        table.ColumnsDefinition(columns =>
                                        {
                                            columns.RelativeColumn(4); 
                                            if (showScheduleColumn)
                                                columns.RelativeColumn(2);
                                            columns.RelativeColumn(2); 
                                            columns.RelativeColumn(2); 
                                            columns.RelativeColumn(3); 
                                        });

                                        table.Header(header =>
                                        {
                                            header.Cell().Background(Colors.Grey.Lighten2).Border(1).BorderColor(Colors.Black).Text("Medication").Bold();

                                            if (showScheduleColumn)
                                                header.Cell().Background(Colors.Grey.Lighten2).Border(1).BorderColor(Colors.Black).Text("Schedule").Bold();

                                            header.Cell().Background(Colors.Grey.Lighten2).Border(1).BorderColor(Colors.Black).Text("Reorder Level").Bold();
                                            header.Cell().Background(Colors.Grey.Lighten2).Border(1).BorderColor(Colors.Black).Text("Quantity").Bold();
                                            header.Cell().Background(Colors.Grey.Lighten2).Border(1).BorderColor(Colors.Black).Text("Notes").Bold();
                                        });

                                        bool alternate = false;
                                        foreach (var med in group)
                                        {
                                            var bgColor = alternate ? Colors.Grey.Lighten5 : Colors.White;

                                            table.Cell().Background(bgColor).Border(1).BorderColor(Colors.Grey.Medium).Text(med.MedicineName);

                                            if (showScheduleColumn)
                                                table.Cell().Background(bgColor).Border(1).BorderColor(Colors.Grey.Medium).Text(med.Schedule.ToString());

                                            table.Cell().Background(bgColor).Border(1).BorderColor(Colors.Grey.Medium).Text(med.ReorderLevel.ToString());
                                            table.Cell().Background(bgColor).Border(1).BorderColor(Colors.Grey.Medium).Text(med.Quantity.ToString());
                                            table.Cell().Background(bgColor).Border(1).BorderColor(Colors.Grey.Medium).Text("");

                                            alternate = !alternate;
                                        }

                                        table.Footer(footer =>
                                        {
                                            uint colSpan = (uint)(showScheduleColumn ? 3 : 2);
                                            footer.Cell().ColumnSpan(colSpan).Background(Colors.Grey.Lighten2).Border(1).BorderColor(Colors.Black).Text("Sub-total:").Bold();
                                            footer.Cell().Background(Colors.Grey.Lighten2).Border(1).BorderColor(Colors.Black).Text(group.Sum(m => m.Quantity).ToString()).Bold();
                                            footer.Cell().Background(Colors.Grey.Lighten2).Border(1).BorderColor(Colors.Black).Text("");
                                        });
                                    });

                                });
                            });

                            column.Item().PaddingBottom(10);
                        }
                    });

                    page.Footer().AlignCenter().Row(row =>
                    {
                        row.RelativeItem().Text(txt =>
                        {
                            txt.Span("Page ");
                            txt.CurrentPageNumber();
                            txt.Span(" / ");
                            txt.TotalPages();
                        });
                    });
                });
            }).GeneratePdf();

            return File(pdfBytes, "application/pdf", $"PharmacyManagerReport_{DateTime.Now:yyyyMMdd}.pdf");
        }
    }
}
