// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ONT_PROJECT.Models;

#nullable disable

namespace ONT_PROJECT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251206074813_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ONT_PROJECT.Models.ActiveIngredient", b =>
                {
                    b.Property<int>("ActiveIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ActiveIngredientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActiveIngredientId"));

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("ActiveIngredientId");

                    b.ToTable("ActiveIngredient", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.ActivityLog", b =>
                {
                    b.Property<int>("ActivityLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActivityLogId"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePerformed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActivityLogId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.BOrder", b =>
                {
                    b.Property<int>("BOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("B_OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BOrderId"));

                    b.Property<DateOnly>("DatePlaced")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateRecieved")
                        .HasColumnType("date");

                    b.Property<int?>("PharmacyManagerId")
                        .HasColumnType("int")
                        .HasColumnName("PharmacyManagerID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.HasKey("BOrderId");

                    b.HasIndex("PharmacyManagerId");

                    b.HasIndex("SupplierId");

                    b.ToTable("B_Order", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.BOrderLine", b =>
                {
                    b.Property<int>("BOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("B_OrderLineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BOrderLineId"));

                    b.Property<int>("BOrderId")
                        .HasColumnType("int")
                        .HasColumnName("B_OrderID");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BOrderLineId");

                    b.HasIndex("BOrderId");

                    b.HasIndex("MedicineId");

                    b.ToTable("B_OrderLine", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.CustomerAllergy", b =>
                {
                    b.Property<int>("CustomerAllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerAllergyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerAllergyId"));

                    b.Property<int>("ActiveIngredientId")
                        .HasColumnType("int")
                        .HasColumnName("ActiveIngredientID");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.HasKey("CustomerAllergyId");

                    b.HasIndex("ActiveIngredientId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerAllergy", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Doctor", b =>
                {
                    b.Property<int>("DoctorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoctorId"));

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PracticeNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.DosageForm", b =>
                {
                    b.Property<int>("FormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FormID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FormId"));

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("FormId");

                    b.ToTable("DosageForm", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.MedIngredient", b =>
                {
                    b.Property<int>("MedIngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedIngredientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedIngredientId"));

                    b.Property<int>("ActiveIngredientId")
                        .HasColumnType("int")
                        .HasColumnName("ActiveIngredientID");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MedIngredientId");

                    b.HasIndex("ActiveIngredientId");

                    b.HasIndex("MedicineId");

                    b.ToTable("MedIngredient", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Medicine", b =>
                {
                    b.Property<int>("MedicineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineId"));

                    b.Property<int>("FormId")
                        .HasColumnType("int")
                        .HasColumnName("FormID");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<double>("SalesPrice")
                        .HasColumnType("float");

                    b.Property<int>("Schedule")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.HasKey("MedicineId");

                    b.HasIndex("FormId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Medicine", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<DateOnly>("DatePlaced")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateRecieved")
                        .HasColumnType("date");

                    b.Property<int?>("PharmacistId")
                        .HasColumnType("int")
                        .HasColumnName("PharmacistID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    b.Property<double>("TotalDue")
                        .HasColumnType("float");

                    b.Property<double>("Vat")
                        .HasColumnType("float")
                        .HasColumnName("VAT");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PharmacistId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.OrderLine", b =>
                {
                    b.Property<int>("OrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderLineID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderLineId"));

                    b.Property<int?>("LineId")
                        .HasColumnType("int")
                        .HasColumnName("LineID");

                    b.Property<double>("LineTotal")
                        .HasColumnType("float");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.HasKey("OrderLineId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLine", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Pharmacist", b =>
                {
                    b.Property<int>("PharmacistId")
                        .HasColumnType("int")
                        .HasColumnName("PharmacistID");

                    b.Property<string>("HealthCounsilRegNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PharmacistId");

                    b.ToTable("Pharmacist", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Pharmacy", b =>
                {
                    b.Property<int>("PharmacyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PharmacyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PharmacyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HealthCounsilRegistrationNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PharmacistId")
                        .HasColumnType("int")
                        .HasColumnName("PharmacistID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<double>("Vatrate")
                        .HasColumnType("float")
                        .HasColumnName("VATRate");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PharmacyId");

                    b.HasIndex("PharmacistId");

                    b.ToTable("Pharmacy", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.PharmacyManager", b =>
                {
                    b.Property<int>("PharmacyManagerId")
                        .HasColumnType("int")
                        .HasColumnName("PharmacyManagerID");

                    b.HasKey("PharmacyManagerId");

                    b.ToTable("PharmacyManager", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescriptionId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int")
                        .HasColumnName("DoctorID");

                    b.Property<int>("PharmacistId")
                        .HasColumnType("int")
                        .HasColumnName("PharmacistID");

                    b.Property<byte[]>("PrescriptionPhoto")
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PrescriptionId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PharmacistId");

                    b.ToTable("Prescription", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.PrescriptionLine", b =>
                {
                    b.Property<int>("PrescriptionLineId")
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionLineID");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MedicineId")
                        .HasColumnType("int")
                        .HasColumnName("MedicineID");

                    b.Property<int>("PrescriptionId")
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Repeats")
                        .HasColumnType("int");

                    b.Property<int?>("RepeatsLeft")
                        .HasColumnType("int");

                    b.Property<int?>("UnprocessedPrescriptionID")
                        .HasColumnType("int");

                    b.HasKey("PrescriptionLineId");

                    b.HasIndex("MedicineId");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionLine", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.RepeatHistory", b =>
                {
                    b.Property<int>("RepeatHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RepeatHistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepeatHistoryId"));

                    b.Property<DateTime>("DateUsed")
                        .HasColumnType("datetime");

                    b.Property<int>("PrescriptionLineId")
                        .HasColumnType("int")
                        .HasColumnName("PrescriptionLineID");

                    b.Property<int>("RepeatsDecremented")
                        .HasColumnType("int");

                    b.HasKey("RepeatHistoryId");

                    b.HasIndex("PrescriptionLineId");

                    b.ToTable("RepeatHistory", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.RepeatRequest", b =>
                {
                    b.Property<int>("RepeatRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepeatRequestId"));

                    b.Property<int>("OrderLineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RepeatRequestId");

                    b.HasIndex("OrderLineId");

                    b.ToTable("RepeatRequest");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SupplierID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("SupplierId");

                    b.ToTable("Supplier", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.TblUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Idnumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IDNumber");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Phone Number");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ResetToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId")
                        .HasName("PK_User");

                    b.ToTable("tblUser", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.UnprocessedPrescription", b =>
                {
                    b.Property<int>("UnprocessedPrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UnprocessedPrescriptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnprocessedPrescriptionId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Dispense")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("PrescriptionPhoto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("UnprocessedPrescriptionId");

                    b.HasIndex("CustomerId");

                    b.ToTable("UnprocessedPrescription", (string)null);
                });

            modelBuilder.Entity("ONT_PROJECT.Models.BOrder", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.PharmacyManager", "PharmacyManager")
                        .WithMany("BOrders")
                        .HasForeignKey("PharmacyManagerId")
                        .HasConstraintName("FK_B_Order_PharmacyManager");

                    b.HasOne("ONT_PROJECT.Models.Supplier", "Supplier")
                        .WithMany("BOrders")
                        .HasForeignKey("SupplierId")
                        .HasConstraintName("FK_B_Order_Supplier");

                    b.Navigation("PharmacyManager");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.BOrderLine", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.BOrder", "BOrder")
                        .WithMany("BOrderLines")
                        .HasForeignKey("BOrderId")
                        .IsRequired()
                        .HasConstraintName("FK_B_OrderLine_B_Order");

                    b.HasOne("ONT_PROJECT.Models.Medicine", "Medicine")
                        .WithMany("BOrderLines")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_B_OrderLine_Medicine");

                    b.Navigation("BOrder");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Customer", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.TblUser", "CustomerNavigation")
                        .WithOne("Customer")
                        .HasForeignKey("ONT_PROJECT.Models.Customer", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Customer_TblUser");

                    b.Navigation("CustomerNavigation");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.CustomerAllergy", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.ActiveIngredient", "ActiveIngredient")
                        .WithMany("CustomerAllergies")
                        .HasForeignKey("ActiveIngredientId")
                        .IsRequired()
                        .HasConstraintName("FK_CustomerAllergy_ActiveIngredient");

                    b.HasOne("ONT_PROJECT.Models.Customer", "Customer")
                        .WithMany("CustomerAllergies")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_CustomerAllergy_Customer");

                    b.Navigation("ActiveIngredient");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.MedIngredient", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.ActiveIngredient", "ActiveIngredient")
                        .WithMany("MedIngredients")
                        .HasForeignKey("ActiveIngredientId")
                        .IsRequired()
                        .HasConstraintName("FK_MedIngredient_ActiveIngredient");

                    b.HasOne("ONT_PROJECT.Models.Medicine", "Medicine")
                        .WithMany("MedIngredients")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_MedIngredient_Medicine");

                    b.Navigation("ActiveIngredient");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Medicine", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.DosageForm", "Form")
                        .WithMany("Medicines")
                        .HasForeignKey("FormId")
                        .IsRequired()
                        .HasConstraintName("FK_Medicine_DosageForm");

                    b.HasOne("ONT_PROJECT.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Order", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Order_Customer");

                    b.HasOne("ONT_PROJECT.Models.Pharmacist", "Pharmacist")
                        .WithMany("Orders")
                        .HasForeignKey("PharmacistId")
                        .HasConstraintName("FK_Order_Pharmacist");

                    b.Navigation("Customer");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.OrderLine", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.Medicine", "Medicine")
                        .WithMany("OrderLines")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderLine_Medicine");

                    b.HasOne("ONT_PROJECT.Models.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderLine_Order");

                    b.Navigation("Medicine");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Pharmacist", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.TblUser", "PharmacistNavigation")
                        .WithOne("Pharmacist")
                        .HasForeignKey("ONT_PROJECT.Models.Pharmacist", "PharmacistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Pharmacist_TblUser");

                    b.Navigation("PharmacistNavigation");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Pharmacy", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.Pharmacist", "Pharmacist")
                        .WithMany("Pharmacies")
                        .HasForeignKey("PharmacistId")
                        .HasConstraintName("FK_Pharmacy_Pharmacist");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.PharmacyManager", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.TblUser", "PharmacyManagerNavigation")
                        .WithOne("PharmacyManager")
                        .HasForeignKey("ONT_PROJECT.Models.PharmacyManager", "PharmacyManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PharmacyManager_TblUser");

                    b.Navigation("PharmacyManagerNavigation");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Prescription", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.Customer", "Customer")
                        .WithMany("Prescriptions")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescription_Customer");

                    b.HasOne("ONT_PROJECT.Models.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescription_Doctor");

                    b.HasOne("ONT_PROJECT.Models.Pharmacist", "Pharmacist")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PharmacistId")
                        .IsRequired()
                        .HasConstraintName("FK_Prescription_Pharmacist");

                    b.Navigation("Customer");

                    b.Navigation("Doctor");

                    b.Navigation("Pharmacist");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.PrescriptionLine", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.Medicine", "Medicine")
                        .WithMany("PrescriptionLines")
                        .HasForeignKey("MedicineId")
                        .IsRequired()
                        .HasConstraintName("FK_PrescriptionLine_Medicine");

                    b.HasOne("ONT_PROJECT.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionLines")
                        .HasForeignKey("PrescriptionId")
                        .IsRequired()
                        .HasConstraintName("FK_PrescriptionLine_Prescription");

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.RepeatHistory", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.PrescriptionLine", "PrescriptionLine")
                        .WithMany("RepeatHistories")
                        .HasForeignKey("PrescriptionLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_RepeatHistory_PrescriptionLine");

                    b.Navigation("PrescriptionLine");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.RepeatRequest", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.OrderLine", "OrderLine")
                        .WithMany()
                        .HasForeignKey("OrderLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderLine");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.UnprocessedPrescription", b =>
                {
                    b.HasOne("ONT_PROJECT.Models.Customer", "Customer")
                        .WithMany("UnprocessedPrescriptions")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_UnprocessedPrescription_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.ActiveIngredient", b =>
                {
                    b.Navigation("CustomerAllergies");

                    b.Navigation("MedIngredients");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.BOrder", b =>
                {
                    b.Navigation("BOrderLines");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Customer", b =>
                {
                    b.Navigation("CustomerAllergies");

                    b.Navigation("Orders");

                    b.Navigation("Prescriptions");

                    b.Navigation("UnprocessedPrescriptions");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Doctor", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.DosageForm", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Medicine", b =>
                {
                    b.Navigation("BOrderLines");

                    b.Navigation("MedIngredients");

                    b.Navigation("OrderLines");

                    b.Navigation("PrescriptionLines");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Order", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Pharmacist", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Pharmacies");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.PharmacyManager", b =>
                {
                    b.Navigation("BOrders");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Prescription", b =>
                {
                    b.Navigation("PrescriptionLines");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.PrescriptionLine", b =>
                {
                    b.Navigation("RepeatHistories");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.Supplier", b =>
                {
                    b.Navigation("BOrders");
                });

            modelBuilder.Entity("ONT_PROJECT.Models.TblUser", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Pharmacist");

                    b.Navigation("PharmacyManager");
                });
#pragma warning restore 612, 618
        }
    }
}
